name: Publish

# Controls when the action will run.
on:
  # Triggers the workflow on new SemVer tags
  push:
    branches:
      - master
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"
      - "v[0-9]+.[0-9]+.[0-9]+-**"

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false

jobs:
  publish:
    uses: SiaFoundation/workflows/.github/workflows/go-publish.yml@master
    secrets: inherit
    with:
      linux-build-args: -tags='timetzdata netgo' -trimpath -a -ldflags '-s -w -linkmode external -extldflags "-static"'
      windows-build-args: -tags='timetzdata netgo' -trimpath -a -ldflags '-s -w -linkmode external -extldflags "-static"'
      macos-build-args: -tags='timetzdata netgo' -trimpath -a -ldflags '-s -w'
      cgo-enabled: 1
      project: walletd
      project-desc: "walletd: The new Sia wallet"
      version-tag: ${{ github.ref_name }}
  upload:
    if: github.event_name == 'push' && startsWith(github.ref_name, 'v')
    runs-on: ubuntu-latest
    needs: 
      - publish
    steps:
      - uses: actions/checkout@v4.2.2
        with:
          fetch-depth: 0
      - name: Download artifacts
        uses: actions/download-artifact@v4.3.0
        with:
          path: artifacts
      - name: Upload artifacts to release
        run: |
          cd artifacts
          gh release upload ${{ github.ref_name }} *
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        continue-on-error: true