name: Release

on:
  pull_request:
    types: [closed]
    branches: [master]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false

jobs:
  release:
    if: (github.head_ref == 'release' && github.event.pull_request.merged == true) || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4.2.2
        with:
          fetch-depth: 0
      - uses: knope-dev/action@407e9ef7c272d2dd53a4e71e39a7839e29933c48
      - run: knope release --verbose
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_PAT }}
      
